baseURL = "http://agate-pris.dev/"
languageCode = "ja-jp"
title = "agate-pris.dev"
theme = "hugo-theme-sam"

[params]
    dateform = "2006-01-02"

[[params.mainMenu]]
    link = "https://twitter.com/agate_pris"
    text = "Twitter"

[[params.mainMenu]]
    link = "https://github.com/agate-pris"
    text = "GitHub"
