name: github pages

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.59.1"
          extended: true

      - name: Build
        run: |
          hugo --cleanDestinationDir --gc --minify &&
          cp ./CNAME ./public/
