name: github pages test

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.59.1"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Build
        run: hugo --cleanDestinationDir --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-test
